config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/coming_soon'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'static_pages#landing_page'

end

app/views/shared/_footer.html.erb
<footer class="footer">
            <div class="container">
            	<div class="row">
            		<div class="col-md-4 col-sm-4 col-xs-6">
            		<ul class="footer-links">
            			<h4>Site Directory</h4>
            			<li><%= link_to "View All", products_path %></li>
                        <li><%= link_to "Special Offers", static_pages_coming_soon_path %>
                        </li>
                        <li><%= link_to "About Us", static_pages_about_path %>
                        </li>
                        <li><%= link_to "Contact Us", static_pages_contact_path %>
                        </li>
            		  </ul>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-6">
                <ul class="footer-contact">
                	<h4>Contact Us</h4>
                	<li>support@site.com</li>
                	<li>1-800-555-5555</li>
                	<li>555 Streetname, City, State 55555</li>
                </ul>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-12">
                <p class="text-center">&copy; Gadget Mart 2015</p>
            </div>
        </div>
    </footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Gadget Mart", root_path, class: "navbar-brand" %>
            </div>
            <div class="navbar-collapse collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-left">  
                    <li><%= link_to "View All", products_path %></li>
                    <li><%= link_to "Deals", static_pages_coming_soon_path %>
                    </li>
                    <li><%= link_to "About", static_pages_about_path %>
                    </li>
                    <li><%= link_to "Contact", static_pages_contact_path %>
                    </li>
                </ul>
                <ul class="nav navbar-nav pull-right">
                        <% if user_signed_in? %>
                            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete, class: 'login') %>
                            </li>
                            <li><%= link_to('Manage Account', edit_user_registration_path, class: 'login') %>
                            </li>
                        <% else %>
                            <li><%= link_to('Sign Up', new_user_registration_path) %></li>
                            <li><%= link_to('Login', new_user_session_path, class: 'login') %></li>
                        <% end %>
                </ul>
                <form class="nav navbar-form navbar-right" role="search">
                        <div class="form-group">
                            <%= form_tag("/products", method: "get") do %>
                            <%= label_tag(:q, "Search:") %>
                            <%= text_field_tag(:q, "", :plceholder => "Enter search terms", class: "form-control search-box") %>
                        </div>
                        <%= submit_tag("Search", class: "btn btn-default") %>
                    <% end %>
                    </li> 
                </ul>
            </div>
            <!-- end navbar collapse -->
        </div>
        <!-- end nav container-->
    </nav>
    <!-- navbar ends here-->

app/views/shared/_stripe_checkout_button.html.erb
<form action="" method="POST">
	<script
	  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
	  data-image="<%= @product.image_url %>"
	  data-name="<%= @product.name %>"
	  data-description="<%= @product.description %>"
	  data-amount="<%= (@product.price * 100).to_i %>">
	</script>
</form>