config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :products do
    resources :comments
  end
  resources :users
  resources :orders, only: [:index, :show, :create, :destroy]

  get 'static_pages/coming_soon'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'static_pages#landing_page'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments
	validates :name, presence: true
	validates :description, presence: true
	validates :image_url, presence: true
	validates :colour, presence: true
	validates :price, presence: true

	def average_rating
		comments.average(:rating).to_f
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  respond_to :json, :html

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name LIKE ?", "%#{search_term}%").paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
    else
      @products = Product.all.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
    end
    respond_with @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_products
    	count = Product.count
    	max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
   		"products/all-#{count}-#{max_updated_at}"
  	end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row review-block">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
                <% if signed_in? && current_user.admin? %>
            		<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, date: { confirm: 'Are you sure? '} %>
            	<% end %>
            </p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, :class => "form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, :class => "form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url, :class => "form_control" %>
  </div>
  <div class="form-group">
    <%= f.label :colour %><br>
    <%= f.text_field :colour, :class => "form_control" %>
  </div>
   <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, :class => "form_control" %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-default" %>
  </div>
</div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <div class="container">

  <h4>Add a review:</h4>
    <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
      <div class="form-group small-comment">
        <%= f.label :body, "Comments" %><br>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="rating">
      </div> 
      <div class="actions">
        <%= f.submit "Submit", class: "btn btn-default" %>
      </div>
  <% end %>
  </div>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
<div class="row product-row">
      <div class="col-md-6 col-sm-6">
        <p><strong><%= product.name %></strong></p>
        <p>Description: <%= product.description %></p>
        <p>Color: <%= product.colour %>
        <h4>$<%= sprintf "%.2f", product.price %></h4>
        <p><%= link_to 'Product Details', product, class: "btn btn-primary" %><br>
        <%= link_to 'Edit', edit_product_path(product), class: "btn btn-info" %>
        <%= link_to 'Delete', product, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>
      <div class="col-md-6 col-sm-6">
        <img src="<%= product.image_url %>" alt="<%= product.name %>" class="thumbnail center-block"/>
      </div>
    </div>
    <% end %>

app/views/products/edit.html.erb
<div class="container">
	<h1 class="page-heading">Edit Product Entry</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @product %> |
	<%= link_to 'Go Back', products_path %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
      <div class="col-md-12">
        <h1 class="page-heading">List of Products</h1>
        <button class="btn btn-primary center-block"><%= link_to 'Add a new product', new_product_path %></button>
  </div>
  <% cache(cache_key_for_products) do %>
    <%= render @products %>
  <% end %>
    <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
</div>

  </div>
</div>

app/views/products/new.html.erb
<div class="container">
	<h1 class="page-heading">Add a Product</h1>

	<%= render 'form' %>

	<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="container product-display page-heading">
	<div class="row">
		<% cache @product do %>
		<div class="col-md-6 col-sm-6">
			<%= image_tag(@product.image_url, class: "center-block thumbnail img-zoom", data_zoom_image: @product.image_url) %>
		</div>

		<div class="col-md-6 col-sm-6">
			<h2><%= @product.name %></h2>
			<% logger.debug "Product: #{@product.name}"%> 
			<h5>Color: <%= @product.colour %></h5>
			<h4>$<%= sprintf "%.2f", @product.price %></h4>
			<p class="italic"><%= @product.description %></p>
			<% end %>
			<p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div></p>
			<%= form_tag "/payments/create" do %>
			<%= hidden_field_tag(:product_id, @product.id) %>
  			<%= render partial: "shared/stripe_checkout_button" %>
<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<%= link_to 'Edit', edit_product_path(@product) %> | 
			<%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' } %> |
			<%= link_to 'Back', products_path %>
		</div>
	</div>
	<div class="row reviews">
		<div class="col-md-9">
			<%= render 'new_comment' %>
		</div>
	</div>

	<div class="row reviews">
		<div class="col-md-9">
			<h4 class="review-heading"><span class="glyphicon glyphicon-star"></span> <u>Customer Reviews</u> <span class="glyphicon glyphicon-star"></span></h4>
			<%= render 'comments' %>
			<%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
		</div>
	</div>
</div>